let TOKEN='',A=[],CATS=[],LINKS=[],SET={},editing=null;const C=window.NETISHIELD_CONFIG,$=x=>document.getElementById(x),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));function b64(s){return btoa(unescape(encodeURIComponent(s)))}function unb64(s){return decodeURIComponent(escape(atob(s.replace(/\n/g,''))))}
async function api(path,opt={}){const r=await fetch('https://api.github.com'+path,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+TOKEN,...(opt.headers||{})}});if(!r.ok)throw Error((await r.text()).slice(0,350));return r.status===204?null:r.json()}
async function read(path){const r=await api(`/repos/${C.owner}/${C.repo}/contents/${path}?ref=${C.branch}`);return {data:JSON.parse(unb64(r.content)),sha:r.sha}}
async function write(path,obj,msg,sha){const body={message:'NetiShield: '+msg,content:b64(JSON.stringify(obj,null,2)+'\n'),branch:C.branch};if(sha)body.sha=sha;return api(`/repos/${C.owner}/${C.repo}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function load(){A=(await read('data/articles.json')).data;CATS=(await read('data/categories.json')).data;LINKS=(await read('data/links.json')).data;SET=(await read('data/settings.json')).data;render()}
function render(){ $('statArticles').textContent=A.length;$('statCats').textContent=CATS.length;$('statLinks').textContent=LINKS.length;$('adminArticles').innerHTML=A.filter(x=>x.title.toLowerCase().includes(($('adminSearch').value||'').toLowerCase())).map(x=>`<div class="admin-item"><div><b>${esc(x.title)}</b><div class="meta">${esc(x.category)} · ${esc(x.slug)}</div></div><div class="admin-actions"><button onclick="editA('${x.id}')">ویرایش</button><button onclick="delA('${x.id}')">حذف</button></div></div>`).join('');$('catList').innerHTML=CATS.map((x,i)=>`<div class="rowitem"><span>${esc(x)}</span><button class="admin-actions" onclick="delCat(${i})">حذف</button></div>`).join('');$('linkListAdmin').innerHTML=LINKS.map((x,i)=>`<div class="rowitem"><span><b>${esc(x.title)}</b><br><small>${esc(x.url)}</small></span><button class="admin-actions" onclick="delLink(${i})">حذف</button></div>`).join('')}
function reset(){editing=null;$('title').value='';$('slug').value='';$('category').value=CATS[0]||'';$('tags').value='';$('cover').value='';$('excerpt').value='';$('content').value='';$('featured').checked=false;preview()}
function preview(){let s=esc($('content').value||'').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/\n\n/g,'<br><br>').replace(/\n/g,'<br>');$('preview').innerHTML=s}
window.editA=id=>{const x=A.find(a=>a.id===id);editing=id;$('title').value=x.title;$('slug').value=x.slug;$('category').value=x.category;$('tags').value=(x.tags||[]).join(',');$('cover').value=x.cover||'';$('excerpt').value=x.excerpt||'';$('content').value=x.content||'';$('featured').checked=!!x.featured;preview();scrollTo({top:300,behavior:'smooth'})}
window.delA=async id=>{if(!confirm('حذف شود؟'))return;const r=await read('data/articles.json');A=A.filter(x=>x.id!==id);await write('data/articles.json',A,'حذف مقاله',r.sha);render()}
window.delCat=async i=>{if(!confirm('دسته حذف شود؟'))return;const r=await read('data/categories.json');CATS.splice(i,1);await write('data/categories.json',CATS,'حذف دسته',r.sha);render()}
window.delLink=async i=>{if(!confirm('لینک حذف شود؟'))return;const r=await read('data/links.json');LINKS.splice(i,1);await write('data/links.json',LINKS,'حذف لینک',r.sha);render()}
$('loginBtn').onclick=async()=>{try{TOKEN=$('token').value.trim();await api(`/repos/${C.owner}/${C.repo}`);$('login').hidden=true;$('dash').hidden=false;$('token').value='';await load()}catch(e){TOKEN='';$('loginMsg').textContent='ورود ناموفق: '+e.message}}
$('logout').onclick=()=>{TOKEN='';$('dash').hidden=true;$('login').hidden=false}
$('newArticle').onclick=reset;$('cancelEdit').onclick=reset;$('content').oninput=preview;$('adminSearch').oninput=render;
$('saveArticle').onclick=async()=>{try{const title=$('title').value.trim(),slug=$('slug').value.trim().toLowerCase().replace(/[^a-z0-9\-\u0600-\u06ff]+/g,'-').replace(/^-|-$/g,'');if(!title||!slug)throw Error('عنوان و slug الزامی است');const item={id:editing||crypto.randomUUID(),slug,title,category:$('category').value.trim()||'عمومی',tags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),cover:$('cover').value.trim(),excerpt:$('excerpt').value.trim(),featured:$('featured').checked,date:new Date().toISOString().slice(0,10),content:$('content').value};if(A.some(x=>x.slug===slug&&x.id!==item.id))throw Error('این slug قبلاً استفاده شده');const r=await read('data/articles.json');if(editing)A[A.findIndex(x=>x.id===editing)]=item;else A.unshift(item);await write('data/articles.json',A,editing?'ویرایش مقاله':'افزودن مقاله',r.sha);$('status').textContent='منتشر شد.';render()}catch(e){$('status').textContent='خطا: '+e.message}}
$('addCat').onclick=async()=>{const v=$('newCat').value.trim();if(!v||CATS.includes(v))return;const r=await read('data/categories.json');CATS.push(v);await write('data/categories.json',CATS,'افزودن دسته',r.sha);$('newCat').value='';render()}
$('addLink').onclick=async()=>{const t=$('linkTitle').value.trim(),u=$('linkUrl').value.trim();if(!t||!u)return;const r=await read('data/links.json');LINKS.push({title:t,url:u,description:$('linkDesc').value.trim(),active:true});await write('data/links.json',LINKS,'افزودن لینک',r.sha);$('linkTitle').value='';$('linkUrl').value='';$('linkDesc').value='';render()}
$('saveSettings').onclick=async()=>{const r=await read('data/settings.json');SET={siteTitle:$('setTitle').value,heroTitle:$('setHero').value,heroText:$('setText').value,about:$('setAbout').value,contact:$('setContact').value};await write('data/settings.json',SET,'ویرایش تنظیمات',r.sha);alert('تنظیمات ذخیره شد')}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.querySelectorAll('.panel').forEach(x=>x.hidden=true);$('tab-'+b.dataset.tab).hidden=false})
